Models/serie5.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Audi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class serie5
    {
        public short id_coche { get; set; }
        public string nombre { get; set; }
        public string modelo { get; set; }
        public short cv { get; set; }
        public string consumo { get; set; }
        public byte[] imagen { get; set; }
    }
}

Controllers/serie3Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Runtime.Remoting.Lifetime;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Audi.Models;
using Rotativa.AspNetCore;

namespace Audi.Controllers
{
    public class serie3Controller : Controller
    {
        
        private audiDeportivoEntities1 db = new audiDeportivoEntities1();

        // GET: serie3
        public ActionResult Index()
        {
            return View(db.serie3.ToList());
        }


        // GET: serie3/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie3 serie3 = db.serie3.Find(id);
            if (serie3 == null)
            {
                return HttpNotFound();
            }
            return View(serie3);
        }

        // GET: serie3/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: serie3/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie3 serie3)
        {
            HttpPostedFileBase FileBase = Request.Files[0];
            if (FileBase.FileName.EndsWith(".jpg")) { 
                WebImage image = new WebImage(FileBase.InputStream); 
                serie3.imagen = image.GetBytes(); } 
            else { ModelState.AddModelError("Imagen", "Solo se admiten imágenes en formato jpg"); }
        
            if (ModelState.IsValid)
            {
                db.serie3.Add(serie3);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serie3);
        }

        // GET: serie3/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie3 serie3 = db.serie3.Find(id);
            if (serie3 == null)
            {
                return HttpNotFound();
            }
            return View(serie3);
        }

        // POST: serie3/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie3 serie3)
        {
           

            if (ModelState.IsValid)
            {
                db.Entry(serie3).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serie3);
        }

        // GET: serie3/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie3 serie3 = db.serie3.Find(id);
            if (serie3 == null)
            {
                return HttpNotFound();
            }
            return View(serie3);
        }

        // POST: serie3/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            serie3 serie3 = db.serie3.Find(id);
            db.serie3.Remove(serie3);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult getImage(int id)
        {
            serie3 tipos = db.serie3.Find(id);
            byte[] byteImage = tipos.imagen;

            MemoryStream memoryStream = new MemoryStream(byteImage);
            try{
                Image image = Image.FromStream(memoryStream);
                memoryStream = new MemoryStream();

                image.Save(memoryStream, ImageFormat.Png);
                memoryStream.Position = 0;

              
            }
            catch
            {

            }
            return File(memoryStream, "image/png");


        }
    }
}

Controllers/serie5Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Audi.Models;

namespace Audi.Controllers
{
    public class serie5Controller : Controller
    {
        private audiDeportivoEntities1 db = new audiDeportivoEntities1();

        // GET: serie5
        public ActionResult Index()
        {
            return View(db.serie5.ToList());
        }

        // GET: serie5/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie5 serie5 = db.serie5.Find(id);
            if (serie5 == null)
            {
                return HttpNotFound();
            }
            return View(serie5);
        }

        // GET: serie5/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: serie5/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie5 serie5)
        {
            HttpPostedFileBase FileBase = Request.Files[0];
            if (FileBase.FileName.EndsWith(".jpg"))
            {
                WebImage image = new WebImage(FileBase.InputStream);
                serie5.imagen = image.GetBytes();
            }
            else { ModelState.AddModelError("Imagen", "Solo se admiten imágenes en formato jpg"); }
            if (ModelState.IsValid)
            {
                db.serie5.Add(serie5);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serie5);
        }

        // GET: serie5/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie5 serie5 = db.serie5.Find(id);
            if (serie5 == null)
            {
                return HttpNotFound();
            }
            return View(serie5);
        }

        // POST: serie5/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie5 serie5)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serie5).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serie5);
        }

        // GET: serie5/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie5 serie5 = db.serie5.Find(id);
            if (serie5 == null)
            {
                return HttpNotFound();
            }
            return View(serie5);
        }

        // POST: serie5/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            serie5 serie5 = db.serie5.Find(id);
            db.serie5.Remove(serie5);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult getImage(int id)
        {
            serie5 tipos = db.serie5.Find(id);
            byte[] byteImage = tipos.imagen;

            MemoryStream memoryStream = new MemoryStream(byteImage);
            try
            {
                Image image = Image.FromStream(memoryStream);
                memoryStream = new MemoryStream();

                image.Save(memoryStream, ImageFormat.Png);
                memoryStream.Position = 0;


            }
            catch
            {

            }
            return File(memoryStream, "image/png");


        }
    }
}

Controllers/serie7Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Audi.Models;

namespace Audi.Controllers
{
    public class serie7Controller : Controller
    {
        private audiDeportivoEntities1 db = new audiDeportivoEntities1();

        // GET: serie7
        public ActionResult Index()
        {
            return View(db.serie7.ToList());
        }

        // GET: serie7/Details/5
        public ActionResult Details(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie7 serie7 = db.serie7.Find(id);
            if (serie7 == null)
            {
                return HttpNotFound();
            }
            return View(serie7);
        }

        // GET: serie7/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: serie7/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie7 serie7)
        {
            HttpPostedFileBase FileBase = Request.Files[0];
            if (FileBase.FileName.EndsWith(".jpg"))
            {
                WebImage image = new WebImage(FileBase.InputStream);
                serie7.imagen = image.GetBytes();
            }
            else { ModelState.AddModelError("Imagen", "Solo se admiten imágenes en formato jpg"); }
            if (ModelState.IsValid)
            {
                db.serie7.Add(serie7);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(serie7);
        }

        // GET: serie7/Edit/5
        public ActionResult Edit(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie7 serie7 = db.serie7.Find(id);
            if (serie7 == null)
            {
                return HttpNotFound();
            }
            return View(serie7);
        }

        // POST: serie7/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_coche,nombre,modelo,cv,consumo,imagen")] serie7 serie7)
        {
            if (ModelState.IsValid)
            {
                db.Entry(serie7).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(serie7);
        }

        // GET: serie7/Delete/5
        public ActionResult Delete(short? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            serie7 serie7 = db.serie7.Find(id);
            if (serie7 == null)
            {
                return HttpNotFound();
            }
            return View(serie7);
        }

        // POST: serie7/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(short id)
        {
            serie7 serie7 = db.serie7.Find(id);
            db.serie7.Remove(serie7);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public ActionResult getImage(int id)
        {
            serie7 tipos = db.serie7.Find(id);
            byte[] byteImage = tipos.imagen;

            MemoryStream memoryStream = new MemoryStream(byteImage);
            try
            {
                Image image = Image.FromStream(memoryStream);
                memoryStream = new MemoryStream();

                image.Save(memoryStream, ImageFormat.Png);
                memoryStream.Position = 0;


            }
            catch
            {

            }
            return File(memoryStream, "image/png");


        }
    }
}

Views/serie5/Create.cshtml
@model Audi.Models.serie5

@{
    ViewBag.Title = "Create";
}
<div class="container mt-4">
    <h2>Crear registro para modelo 5</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">ID de Coche</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.id_coche, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id_coche, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <label class="control-label col-md-2">Nombre</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <label class="control-label col-md-2">Modelo</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <label class="control-label col-md-2">CV</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.cv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <label class="control-label col-md-2">Consumo</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.consumo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.consumo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mt-3">
            <label class="control-label col-md-2">Imagen</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })
                <div class="input-group">
                    <input type="file" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
                </div>
                @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group my-4">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-primary border" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Volver a la lista", "Index", new { area = "" }, new { @class = "btn btn-light border border-dark" })
    </div>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

Views/serie5/Delete.cshtml
@model Audi.Models.serie5

@{
    ViewBag.Title = "Delete";
}

<div class="container">
    <h2 class="py-3">Eliminar registro del modelo 5</h2>
    <h4>Registro @Html.DisplayFor(model => model.id_coche)</h4>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.nombre)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.modelo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.modelo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.cv)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cv)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.consumo)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.consumo)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.imagen)
            </dt>

            <dd>
                @* @Html.DisplayFor(modelItem => item.imagen)*@
                <img width="150px" src="@Url.Action("getImage","serie3", new { id= Model.id_coche})" />
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color py-3">
                <input type="submit" value="Delete" class="btn btn-danger border border-dark" /> |
                @Html.ActionLink("Volver a la lista", "Index", new { area = "" }, new { @class = "btn btn-light border border-dark" })
            </div>
        }
    </div>
</div>

Views/serie5/Details.cshtml
@model Audi.Models.serie5

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <h2>Detalles del modelo 5</h2>

    <div>
        <h4>Registro @Html.DisplayFor(model => model.id_coche)</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Nombre
            </dt>

            <dd>
                @Html.DisplayFor(model => model.nombre)
            </dd>

            <dt>
                Modelo
            </dt>

            <dd>
                @Html.DisplayFor(model => model.modelo)
            </dd>

            <dt>
                CV
            </dt>

            <dd>
                @Html.DisplayFor(model => model.cv)
            </dd>

            <dt>
                Consumo
            </dt>

            <dd>
                @Html.DisplayFor(model => model.consumo)
            </dd>

            <dt>
                Imagen
            </dt>

            <dd>
                @* @Html.DisplayFor(modelItem => item.imagen)*@
                <img width="150px" src="@Url.Action("getImage","serie7", new { id= Model.id_coche})" />
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Editar", "Edit", new { id = Model.id_coche }, new { @class = "btn btn-primary border border-dark" }) 
        @Html.ActionLink("Volver a la lista", "Index", new { area = "" }, new { @class = "btn btn-light border border-dark" })
    </p>
</div>

Views/serie5/Edit.cshtml
@model Audi.Models.serie5

@{
    ViewBag.Title = "Edit";
}

<div class="container">
    <h2 class="mt-4">Editar registro @Html.DisplayFor(model => model.id_coche)</h2>


    @using (Html.BeginForm("Edit", "serie5", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id_coche)

    <div class="form-group">
        Nombre
        <div class="col-md-10">
            @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group pt-3">
        Modelo
        <div class="col-md-10">
            @Html.EditorFor(model => model.modelo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.modelo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group pt-3">
        CV
        <div class="col-md-10">
            @Html.EditorFor(model => model.cv, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.cv, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group pt-3">
        Consumo
        <div class="col-md-10">
            @Html.EditorFor(model => model.consumo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.consumo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group pt-3">
        Imagen
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.imagen, new { htmlAttributes = new { @class = "form-control" } })*@
            <img width="100px" src="@Url.Action("getImage","serie5", new { id= Model.id_coche})" />
            @Html.ValidationMessageFor(model => model.imagen, "", new { @class = "text-danger" })
            <div class="input-group">
                <input type="file" class="form-control" id="inputGroupFile04" aria-describedby="inputGroupFileAddon04" aria-label="Upload">
            </div>
        </div>
    </div>

    <div class="form-group pt-3">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-primary border border-dark" />
        </div>
    </div>
</div>
    }

    <div class="py-3">
        @Html.ActionLink("Volver a la lista", "Index", new { area = "" }, new { @class = "btn btn-light border border-dark" })
    </div>

</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/serie5/Index.cshtml
@model IEnumerable<Audi.Models.serie5>

@{
    ViewBag.Title = "Index";
}

<div class="container">

    <h2 class="py-2">Listado de coches del Modelo 5</h2>

    <p>@Html.ActionLink("Crear nuevo registro", "Create", new { area = "" }, new { @class = "btn btn-light border border-dark" })</p>
    <table class="table table-striped">
        <tr>
            <th>
                ID
            </th>
            <th>
                Nombre
            </th>
            <th>
                Modelo
            </th>
            <th>
                CV
            </th>
            <th>
                Consumo
            </th>
            <th>
                Imagen
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.id_coche)

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.modelo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.cv)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.consumo)
                </td>
                <td>
                    @* @Html.DisplayFor(modelItem => item.imagen)*@
                    <img width="150px" src="@Url.Action("getImage","serie5", new { id= item.id_coche})" />
                </td>
                <td>
                    @Html.ActionLink("Editar", "Edit", new { id = item.id_coche }, new { @class = "btn btn-primary border border-dark" }) 
                    @Html.ActionLink("Detalles", "Details", new { id = item.id_coche }, new { @class = "btn btn-primary border border-dark" }) 
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.id_coche }, new { @class = "btn btn-primary border border-dark" })
                </td>
            </tr>
        }

    </table>
</div>